version: "3.8"
networks: 
  rede1:
    driver:   
      bridge
services: 
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: potential_crud
      POSTGRES_PASSWORD: "12345"
    ports: 
      - "5432:5432"
    networks: 
      - rede1

  api:
    container_name: api
    build:
      "./api"
    restart: always
    volumes: 
      - ./api:/app/api
    ports: 
      - "4000:4000"
    depends_on: 
      - db
    networks: 
      - rede1
  # front:
  #   build: 
  #     "./front"
  #   container_name: front
  #   restart: always
  #   volumes: 
  #     - ./front:/app/front
  #   ports: 
  #     - "8080:8080"
    # depends_on: 
    #   - api